export const REPORTS_GET_ALL_REQUEST = 'REPORTS_GET_ALL_REQUEST';
export const REPORTS_GET_ALL_SUCCESS = 'REPORTS_GET_ALL_SUCCESS';
export const REPORTS_GET_ALL_FAILURE = 'REPORTS_GET_ALL_FAILURE';

export const REPORTS_GET_ONE_REQUEST = 'REPORTS_GET_ONE_REQUEST';
export const REPORTS_GET_ONE_SUCCESS = 'REPORTS_GET_ONE_SUCCESS';
export const REPORTS_GET_ONE_FAILURE = 'REPORTS_GET_ONE_FAILURE';

export const REPORTS_BY_CAR_REQUEST = 'REPORTS_BY_CAR_REQUEST';
export const REPORTS_BY_CAR_SUCCESS = 'REPORTS_BY_CAR_SUCCESS';
export const REPORTS_BY_CAR_FAILURE = 'REPORTS_BY_CAR_FAILURE';
