export const CARS_GETALL_REQUEST = 'CARS_GETALL_REQUEST';
export const CARS_GETALL_SUCCESS = 'CARS_GETALL_SUCCESS';
export const CARS_GETALL_FAILURE = 'CARS_GETALL_FAILURE';

export const CAR_SAVE_REQUEST = 'CAR_SAVE_REQUEST';
export const CAR_SAVE_SUCCESS = 'CAR_SAVE_SUCCESS';
export const CAR_SAVE_FAILURE = 'CAR_SAVE_FAILURE';

export const CAR_INFO_REQUEST = 'CAR_INFO_REQUEST';
export const CAR_INFO_SUCCESS = 'CAR_INFO_SUCCESS';
export const CAR_INFO_FAILURE = 'CAR_INFO_FAILURE';
