export const CARS_GETALL_REQUEST = 'CARS_GETALL_REQUEST';
export const CARS_GETALL_SUCCESS = 'CARS_GETALL_SUCCESS';
export const CARS_GETALL_FAILURE = 'CARS_GETALL_FAILURE';

export const CAR_SAVE_REQUEST = 'CAR_SAVE_REQUEST';
export const CAR_SAVE_SUCCESS = 'CAR_SAVE_SUCCESS';
export const CAR_SAVE_FAILURE = 'CAR_SAVE_FAILURE';

export const CAR_INFO_REQUEST = 'CAR_INFO_REQUEST';
export const CAR_INFO_SUCCESS = 'CAR_INFO_SUCCESS';
export const CAR_INFO_FAILURE = 'CAR_INFO_FAILURE';

export const SET_CAR_EDIT_REQUEST = 'SET_CAR_EDIT_REQUEST';
export const SET_CAR_EDIT_SUCCESS = 'SET_CAR_EDIT_SUCCESS';
export const SET_CAR_EDIT_FAILURE = 'SET_CAR_EDIT_FAILURE';

export const EDIT_CAR_INFORMATION_REQUEST = 'EDIT_CAR_INFORMATION_REQUEST';
export const EDIT_CAR_INFORMATION_SUCCESS = 'EDIT_CAR_INFORMATION_SUCCESS';
export const EDIT_CAR_INFORMATION_FAILURE = 'EDIT_CAR_INFORMATION_FAILURE';
